### ISSUE TITLE
How to capture multiple screens

### ISSUE THREAD

**Issue by tutufan** [yinkaisheng/Python-UIAutomation-for-Windows#101]
I have multiple screens, but only capture master screen, how to capture slave screen?

**Comment by yinkaisheng** [comment]
uiautomation doesn't have API that can get multiple screens' positions.
but if you have the multiple screens' positions, you can capture multiple screenshots by uiautomation.

Suppose you have two 1080p screens.
Normally the master screen position will be 0,0,1920,1080, the second screen position will be 1920,0,3840,1080.
auto.GetRootControl().BoundingRectangle only returns the master screen position.
>>>desktop = auto.GetRootControl()
>>>print(desktop.BoundingRectangle)
(0,0,1920,1080)[1920x1080]

But if you call desktop.CaptureToImage('desk2.png',1920,0,1920,1080), it will capture the second screen successfully.

If you call desktop.CaptureToImage('desk-1and2.png',0,0,1920*2,1080), you will get one picture that contains two screens.

You need to get multiple screens' positions via Win32API or find a python module that can do that,
then you can capture the second screen by its position.

I may add the ability to get multiple screens' positions to uiautomation later.

**Comment by tutufan** [comment]
Thank you

**Comment by yinkaisheng** [comment]
加了 GetMonitorsRect

**Comment by Harry2010410** [comment]
@yinkaisheng 大佬，现在有个问题，如果将txt拖到副屏，在Click关闭按钮时，获取到rect是0，0，0，0 ，就关闭失败了，看大佬是否能看下
