### ISSUE TITLE
窗口最小化问题，请修改

### ISSUE THREAD

**Issue by Harry2010410** [yinkaisheng/Python-UIAutomation-for-Windows#111]
大佬，在使用过程中发现个小问题。窗口最小化方法Minimize中，调用的是还原窗口的关键字，希望大佬有时间修复下，多谢啦。

def Minimize(self, waitTime: float = OPERATION_WAIT_TIME) -> bool:
        if self.IsTopLevel():
            return self.ShowWindow(SW.Restore, waitTime)
        return False

**Comment by Harry2010410** [comment]
@yinkaisheng  大佬，有时间修复下呀

**Comment by yinkaisheng** [comment]
fixed
