### ISSUE TITLE
关于SendKsys热键组合键操作

### ISSUE THREAD

**Issue by Harry2010410** [yinkaisheng/Python-UIAutomation-for-Windows#116]
通过SendKeys发送热键组合键时，没有生效，比如uiautomation.SendKeys("{Ctrl}{Alt}{Delete}"),希望大佬在不忙的时候帮忙瞄一下，多谢啦!!
@yinkaisheng

**Comment by yinkaisheng** [comment]
不是bug，由于安全原因，Ctrl+Alt+Delete, Win+L 不能用模拟按键触发。

**Comment by Harry2010410** [comment]
好的，多谢大佬
