### ISSUE TITLE
_ctypes.COMError: (-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))

### ISSUE THREAD

**Issue by JesseAZhou** [yinkaisheng/Python-UIAutomation-for-Windows#117]
你好，当我使用到 Exists() 先判断我要找的control是否存在时，偶尔会出现标题体现的错误（虚拟机中win7/10都正常，但是我将代码转发给其他的win10运行后会出现）。
它的错误行在：
Exists()->line 5854 FindControl ->line 7679 for child, depth in WalkControl -> line 7555 ->
uiautomation\uiautomation.py", line 5726, in GetFirstChildControl
ele = _AutomationClient.instance().ViewWalker.GetFirstChildElement(self.Element)
网上搜索到的类似报错似乎是和跨线程调用有关，但是我调用的代码中没有涉及到，是否是调用MS UIA接口产生的？
请问我在用Exist()或 GetFirstChildControl()的时候该如何规避这个COMError呢？

**Comment by JesseAZhou** [comment]
后续发现是我调用前使用了tkinter弹了一个messageBox关闭后仍然导致卡住了后续的线程

**Comment by 643364103** [comment]
How to fix ?
I also have this problem
