### ISSUE TITLE
ComboBox Select

### ISSUE THREAD

**Issue by tiger902** [yinkaisheng/Python-UIAutomation-for-Windows#119]
ComboBox Select 函数支不支持正则表达式，或者index?

**Comment by yinkaisheng** [comment]
使用Select(condition=...) 在lambda里自定义条件

**Comment by tiger902** [comment]
> 使用Select(condition=...) 在lambda里自定义条件

你好，我刚学Python不久，不太会用。
假如itemname = "        OOK       " ,OOK的前后有随机空格数量，该怎么怎么调用Select函数呢，谢谢

**Comment by yinkaisheng** [comment]
参考 #158
