### ISSUE TITLE
调用Exists时异常：(-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))

### ISSUE THREAD

**Issue by frh16** [yinkaisheng/Python-UIAutomation-for-Windows#122]
反复新建txt

用Exists判断新建（未命名状态）的txt是否存在：list_item.Exists(6, 1)
一定几率抛异常：(-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))

我试过以下办法，都不能解决：
1. try重试，有时几秒后重试恢复，可以正常返回。但有时几秒重试一次，100秒后还是抛异常。
2. 把代码放到auto.InitializeUIAutomationInCurrentThread()和auto.UninitializeUIAutomationInCurrentThread()中间

win10 64 pro
python 3.7.0

Traceback (most recent call last):
  File "D:/work/workspace/PycharmProjects/Test190628/hello2.py", line 44, in <module>
    create_file()
  File "D:/work/workspace/PycharmProjects/Test190628/hello2.py", line 16, in create_file
    assert_rename_control_exist()
  File "D:/work/workspace/PycharmProjects/Test190628/hello2.py", line 30, in assert_rename_control_exist
    is_item_exist = list_item.Exists(6, 1)
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5846, in Exists
    if prev and not prev._element and not prev.Exists(maxSearchSeconds, searchIntervalSeconds):
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5846, in Exists
    if prev and not prev._element and not prev.Exists(maxSearchSeconds, searchIntervalSeconds):
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5846, in Exists
    if prev and not prev._element and not prev.Exists(maxSearchSeconds, searchIntervalSeconds):
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5854, in Exists
    control = FindControl(self.searchFromControl, self._CompareFunction, self.searchDepth, False, self.foundIndex)
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 7679, in FindControl
    for child, depth in WalkControl(control, findFromSelf, maxDepth):
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 7555, in WalkControl
    child = control.GetFirstChildControl()
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5726, in GetFirstChildControl
    ele = _AutomationClient.instance().ViewWalker.GetFirstChildElement(self.Element)
**_ctypes.COMError: (-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))**

import uiautomation as auto
import time
from pywinauto import keyboard

cur_window_handle = 0x0

def create_file():
    cur_window = auto.ControlFromHandle(cur_window_handle)
    cur_window.SetFocus()
    cur_window.SplitButtonControl(Name='新建项目').Click(simulateMove=False)
    time.sleep(2)
    cur_window.MenuItemControl(Name='文本文档').Click(simulateMove=False)
    assert_rename_control_exist()
    keyboard.SendKeys('{ENTER}')

def assert_rename_control_exist():
    cur_window = auto.ControlFromHandle(cur_window_handle)
    tab_window = cur_window.PaneControl(ClassName='ShellTabWindowClass', searchDepth=1)
    main = tab_window.PaneControl(AutomationId='main')  # 浏览器窗格
    layout = main.PaneControl(AutomationId='FolderLayoutContainer', searchDepth=1)
    list_view = layout.PaneControl(AutomationId='listview', searchDepth=1)
    items_view = list_view.ListControl(ClassName='UIItemsView', searchDepth=1)
    list_item = items_view.EditControl(ClassName='UIRenameTextElement', searchDepth=1)
    assert = **list_item.Exists(6, 1)**

def update_window_handle():
    global cur_window_handle
    tgt_window = auto.WindowControl(ClassName='CabinetWClass', searchDepth=1)
    cur_window_handle = tgt_window.NativeWindowHandle

if __name__ == '__main__':
    update_window_handle()
    for i in range(100):
        create_file()
        time.sleep(1)

[code.txt](https://github.com/yinkaisheng/Python-UIAutomation-for-Windows/files/4835896/hello.txt)

**Comment by YiFeng0755** [comment]
你这个问题解决了吗

**Comment by YiFeng0755** [comment]
@frh16 你这个问题解决了吗

**Comment by frh16** [comment]
> @frh16 你这个问题解决了吗

没真正解决，现在我的代码里list_item.Exists(6, 1)前sleep2秒，再每隔3秒重试几次

**Comment by frh16** [comment]
> @frh16 你这个问题解决了吗

没真正解决，现在我的代码里list_item.Exists(0,0)前sleep2秒，再每隔3秒重试1次，10秒超时
