### ISSUE TITLE
automation.py -h不能运行，每次都是打开文本文件，辛苦帮忙看看，多谢！！！

### ISSUE THREAD

**Issue by dulangnwpu** [yinkaisheng/Python-UIAutomation-for-Windows#123]
automation.py -h不能运行，每次都是打开文本文件，辛苦帮忙看看，多谢！！！
我是使用anaconda3安装的python，然后pip 安装uiautomation，  使用pycharm运行程序的
每次在cmd上运行automation.py -h  都是在pycharm里面打开automation的源程序文件

**Comment by gongxic** [comment]
@dulangnwpu  怎么解决的啊 我要遇到这个问题
