### ISSUE TITLE
查看网易云音乐客户端页面结构报错

### ISSUE THREAD

**Issue by yangyechi** [yinkaisheng/Python-UIAutomation-for-Windows#135]
**Uiautomation version:** 2.0.7
**Python version:** 3.9.0
**Error log:**
D:\Python3.9.0\Scripts>python automation.py -t 3
UIAutomation 2.0.7 (Python 3.9.0, 64 bit)
please wait for 3 seconds

2020-10-27 20:37:43.552 automation.py[75] main -> Starts, Current Cursor Position: (818, 353)
ControlType: PaneControl    ClassName: #32769    AutomationId:     Rect: (0,0,1280,800)[1280x800]    Name: 桌面 1    Handle: 0x10010(65552)    Depth: 0    SupportedPattern: LegacyIAccessiblePattern
    ControlType: WindowControl    ClassName: OrpheusBrowserHost    AutomationId:     Rect: (-8,-8,1288,768)[1296x776]    Name: 回头太难 - 张学友    Handle: 0x50644(329284)    Depth: 1    SupportedPattern: LegacyIAccessiblePattern TransformPattern WindowPattern
        ControlType: PaneControl    ClassName: CefBrowserWindow    AutomationId:     Rect: (0,0,1280,760)[1280x760]    Name:     Handle: 0x7062E(460334)    Depth: 2    SupportedPattern: LegacyIAccessiblePattern
            ControlType: WindowControl    ClassName: Chrome_WidgetWin_0    AutomationId:     Rect: (0,0,1280,760)[1280x760]    Name:     Handle: 0x70638(460344)    Depth: 3    SupportedPattern: LegacyIAccessiblePattern
                ControlType: CustomControl    ClassName:     AutomationId:     Rect: (0,0,1280,760)[1280x760]    Name:     Handle: 0x0(0)    Depth: 4    SupportedPattern: LegacyIAccessiblePattern
                    ControlType: DocumentControl    ClassName:     AutomationId:     Rect: (0,0,1022,670)[1022x670]    Name:     Handle: 0x0(0)    Depth: 5    TextPattern.Text: Traceback (most recent call last):
  File "D:\Python3.9.0\Scripts\automation.py", line 113, in <module>
    main()
  File "D:\Python3.9.0\Scripts\automation.py", line 109, in main
    auto.EnumAndLogControl(control, depth, showAllName, startDepth=indent)
  File "D:\Python3.9.0\lib\site-packages\uiautomation\uiautomation.py", line 7706, in EnumAndLogControl
    LogControl(c, d + startDepth, showAllName)
  File "D:\Python3.9.0\lib\site-packages\uiautomation\uiautomation.py", line 7690, in LogControl
    Logger.Write(pt.DocumentRange.GetText(30), ConsoleColor.DarkGreen)
  File "D:\Python3.9.0\lib\site-packages\uiautomation\uiautomation.py", line 4754, in DocumentRange
    return TextRange(self.pattern.DocumentRange)
_ctypes.COMError: (-2147467259, '未指定的错误', (None, None, None, 0, None))

**UISpy Structure：**
![UISpy](https://user-images.githubusercontent.com/33744122/97304435-abb72680-1896-11eb-8df9-4615b53efc00.PNG)

**Comment by yinkaisheng** [comment]
fixed
