### ISSUE TITLE
你的例子存在问题

### ISSUE THREAD

**Issue by 910387466** [yinkaisheng/Python-UIAutomation-for-Windows#14]
你的例子里调用SetActive(),不对， 你的例子错了，你的源码中这个SetActive()方法是写在WindowControl这个类里的， 你的调用没有从这个类里继承，就会报错~！

**Comment by nxz91** [comment]
No entiendo nada jajaja

**Comment by 910387466** [comment]
You go to see his uiautomation source, and then look at the few examples he gave it to know！
