### ISSUE TITLE
不能对combox连续操作两次

### ISSUE THREAD

**Issue by weridolin** [yinkaisheng/Python-UIAutomation-for-Windows#141]
在测试过程中发现一个bug
比如
1先对combox设置一个值，
2再对combox 进行取值，
或者
1先对combox 进行取值，
2再对combox设置一个值，

会出现第二个操作找不到控件的报错(Find Control Timeout: {ControlType: PaneControl})

测试环境如下
操作系统：WIN 10 
PYTHON版本 3.73

操作对象：teamview 界面的计算机ID界面输入框

  "ui_tree": [
            {"name": "伙伴ID", "type": 50003, "control_type_name": "ComboBoxControl", "classname": "ATL:040B1768",
             "region": [1050, 320, 1320, 360], "index": 1, "found_index": 1, "ui_tree": []},
            {"name": "", "type": 50033, "control_type_name": "PaneControl",
             "classname": "OutgoingRemoteControlComponentView", "region": [1050, 242, 1320, 592], "index": 3,
             "found_index": 1, "ui_tree": []},
            {"name": "连接准备已就绪(安全连接)", "type": 50033, "control_type_name": "PaneControl",
             "classname": "MainWindowRemoteControlPage", "region": [725, 227, 1662, 771], "index": 4, "found_index": 1,
             "ui_tree": []}], "pos_x": 1277, "pos_y": 350}]

设置值是用 控件的GetValuePattern.SetValue和Select混合使用
取值是用 控件的GetValuePattern.value

**Comment by yinkaisheng** [comment]
你写个脚本对记事本的字体combobox操作下看看，写个复现代码贴上来
格式->字体
![image](https://user-images.githubusercontent.com/5846696/103058089-3b016180-45dc-11eb-9ffb-2f5af6b3fef5.png)
