### ISSUE TITLE
Question about InvokePattern.Invoke

### ISSUE THREAD

**Issue by geidien** [yinkaisheng/Python-UIAutomation-for-Windows#149]
Could you give an example of how to use InvokePattern.Invoke??

I'm relatively new to this and have read all of your documentation, and I would really appreciate the help as a newbie. I have tried several other places to find an answer.
https://stackoverflow.com/questions/59980831/clicking-on-save-as-option-in-internet-explorer-using-python

I have been able to do this same thing with excel VBA referencing the UIautomation core. I am no programmer, but I am trying!

This is what I have for my code. I have a special use case of Internet Explorer where I need to Select the Save Notification Button. The SaveBtn.Click() works fine but I would prefer to try it with the Invoke method.
![image](https://user-images.githubusercontent.com/72724782/104550160-da24e200-55f9-11eb-9dc9-eaf7e60c549d.png)

#*************************************************************************************
import uiautomation as uia

#Click the Saveas Button on Internet Explorer Window
objIE = uia.WindowControl(searchDepth=1, Name='FRSE - Internet Explorer')
Pane = objIE.PaneControl(searchDepth=1, ClassName = 'Frame Notification Bar')
ToolBar = Pane.ToolBarControl(SearchDepth=1, Name = 'Notification')
SaveBtn = ToolBar.SplitButtonControl(SearchDepth=1, Name = 'Save')

Sve = SaveBtn.GetInvokePattern
Svepattern = uia.InvokePattern(pattern=Sve)
Svepattern.Invoke
#SaveBtn.Click()

**Comment by demoxana** [comment]
....
SaveBtn = ToolBar.SplitButtonControl(SearchDepth=1, Name = 'Save')
SaveBtn.GetInvokePattern().Invoke()
