### ISSUE TITLE
UTF-16 encode/decode issue

### ISSUE THREAD

**Issue by longk15t** [yinkaisheng/Python-UIAutomation-for-Windows#15]
Hey bro! Thanks for your script. But

I got an issue, I was going to install Intel RealSense SDK core installer but your automation.py does not capture any controls of this window. I got this error message 
![image](https://cloud.githubusercontent.com/assets/6722910/20873123/11f09624-bad7-11e6-8dd7-975e9a491257.png)

This is the windows I need to interact
![image](https://cloud.githubusercontent.com/assets/6722910/20873136/3af3490e-bad7-11e6-826b-4e21174f8d35.png)

I guess it includes character ™ and ®so it does not work.

**Comment by yinkaisheng** [comment]
See the log file @AutomationLog.txt. The controls' information are also written to the log file.
™ and ® can't be printed in console, but they are right in the log file.

![2016-12-05 11_57_39- _ automation](https://cloud.githubusercontent.com/assets/5846696/20873453/5d0d3940-bae2-11e6-9de7-7e304f939879.png)

**Comment by longk15t** [comment]
Right, but I checked if it exists by my code and it show some errors about encoding/decoding issue like: 

> SyntaxError: Non-ASCII character '\xc2' in file ....py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

searched google and I tried to add this like `# -*- coding: utf-8 -*-` to top of my script file but it shows

> automation.py:1842: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   if self.searchPorpertyDict['Name'] != control.Name:
> False

It said False, that mean this windows does not exist.

**Comment by yinkaisheng** [comment]
Make sure your script file format is utf-8 and use unicode string for python 2.

The following code works well both on python 2 and python 3. If I remove the **u** before '™ and ®', I can reproduce the same bug as yours on python 2.

`
# -*- coding: utf-8 -*-
import subprocess
import uiautomation as automation

def main():
    title = u'™ and ®'
    subprocess.Popen('notepad')
    window = automation.WindowControl(searchDepth= 1, ClassName = 'Notepad')
    window.SetWindowText(title)
    newWindow = automation.WindowControl(searchDepth= 1, ClassName = 'Notepad', Name = title)
    if newWindow.Exists(0, 0):
        newWindow.EditControl().SendKeys('notepad found')

if __name__ == '__main__':
    main()
`

**Comment by longk15t** [comment]
no luck man :( it say this window does not exist.

**Comment by longk15t** [comment]
I tried other solutions like SendKey (e.g VK_RETURN, VK_TAB, ...) to interact with child controls but still no luck :( any idea ? except mouse click.
