### ISSUE TITLE
EditControl 有没有清除原有字符的方法？

### ISSUE THREAD

**Issue by Deteriorator** [yinkaisheng/Python-UIAutomation-for-Windows#156]
Hi， 你好，

我这里有一种情景，EditControl 中会保留上次输入的结果，但是我每次需要输入新的内容，直接使用SendKeys方法是在其后追加内容，因此想问一下是否有个方法能清除原有的字符？

Thanks

**Comment by Deteriorator** [comment]
目前使用Ctrl+a全选，然后用SendKeys方法添加内容

**Comment by yinkaisheng** [comment]
edit.GetValuePattern().SetValue('')

**Comment by Deteriorator** [comment]
> edit.GetValuePattern().SetValue('')

多谢

**Comment by UshioYu** [comment]
edit.GetValuePattern().SetValue('')，如果控件执行SetValue报错，用edit.SendKeys('{Ctrl}a{Delete}' )
