### ISSUE TITLE
How to select the ComboBoxControl with the index? 怎么按照顺序索引选择下拉框？

### ISSUE THREAD

**Issue by dinglei0719** [yinkaisheng/Python-UIAutomation-for-Windows#158]
Take the combobox in Xshell for example

I find the the setvalue function take the name (like TELENT) of the selected item, but I want to select the first one without known the name?

How can I do that?

如何实现通过索引选择下拉框的选项。例如，在Xshell的协议中选择下拉框中的第1个，不管第1个是什么？
![image](https://user-images.githubusercontent.com/6258286/114979996-5b706700-9ebe-11eb-8407-cd89831f995d.png)

**Comment by yinkaisheng** [comment]
更新最新代码。
使用
combox.Select(condition=lambda itemText: True)
如果要选择第n个，需要用下面这个
index = 0
selectIndex = n
def selectFirst(itemText: str):
    nonlocal index
    print(itemText, index)
    if index == selectIndex:
        return True
    index += 1
combox.Select(condition=selectFirst)

**Comment by zhongzhichun** [comment]
按照给的代码好像对于下拉的列表，选择需要的选项并没有生效
代码：
import uiautomation as auto

print("get cobra app")
cobra = auto.WindowControl(AutomationId="FrmMain", Depth=1)

comboIndex = 1
selectIndex = 2

def selectNth(itemText):
  global comboIndex
  print(itemText, comboIndex)
  if comboIndex == selectIndex:
    return True
  comboIndex += 1

print("get price type")
ptype = cobra.ComboBoxControl(AutomationId="cmbOrderType", Depth=4)
ptype.Select(condition=selectNth)
ptype.Select("MKT")
执行效果图：
![CobraGUI_pSBvpH8kP5](https://github.com/yinkaisheng/Python-UIAutomation-for-Windows/assets/12390350/e4495960-aaf4-4c48-a202-e42680d0ed1d)

需要选择mkt但一直选的是lmt,是哪里不对吗
