### ISSUE TITLE
Not getting DragPattern and DropTargetPattern

### ISSUE THREAD

**Issue by sartajg** [yinkaisheng/Python-UIAutomation-for-Windows#159]
Hi @yinkaisheng,
I am using `control = auto.GetFocusedControl()` or other control but not getting `DragPattern `and `DropTargetPattern`.
I have checked inside the library, and saw, pattern interface was blocked for these 2. Then I tried to unblock these but still not helped. 
Then I observed, `control` itself is not returning any pattern for drag and drop because `class ControlType:` doesn't have entry of drag and drop control.

Let me clarify question 1 more time, in case above is puzzled.
How to get `DragPattern `and `DropTargetPattern` from control?

**Comment by yinkaisheng** [comment]
if a control supports DragPattern or DropTargetPattern
use 
```
pt=control.GetPattern(auto.PatternId.DragPattern) #or auto.PatternId.DropTargetPattern
if pt:
    print(pt.IsGrabbed)
```
[Control Pattern Mapping for UI Automation Clients](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-controlpatternmapping), Microsoft doc doesn't show which control must support DragPattern and DropTargetPattern, so there is no GetDragPattern and GetDropTargetPattern in controls' methods.

**Comment by sartajg** [comment]
``Thanks for the quick response @yinkaisheng.
I was checking your solution, but the problem is, as I already mentioned above, none of the control is having drag&drop pattern and because of that if I will try to extract from control, I will get None.

Is there anything I need to register like below code for drag and drop.
`self.IUIAutomation = comtypes.client.CreateObject("{ff48dba4-60ef-4201-aa87-54103eef594e}", interface=self.UIAutomationCore.IUIAutomation)`

I am doing drag&drop in Chrome browser using gmail. Tried with windows File explorer too but no luck. I want this to be captured, so that I can get captured object like `print(pt.IsGrabbed)`

**Comment by yinkaisheng** [comment]
You don't need any code to register.
Microsoft Inspect.exe also shows that Chrome and File explorer don't support drag and drop patterns.
Maybe they don't implement drag and drop patterns.
Actually I have never seen a control that supports drag and drop patterns.

**Comment by sartajg** [comment]
Since it is not supported and probably will be supported in future, so I am closing this ticket for now.
Thanks @yinkaisheng for quick response
