### ISSUE TITLE
There is some trouble with AutomationClient.dll has been loaded

### ISSUE THREAD

**Issue by Kunkka1988** [yinkaisheng/Python-UIAutomation-for-Windows#16]
Hi Kaisheng,

In win10, it will show the "WindowsError: [Error 126] The specified module could not be found" hints after processed "import uiautomation as automation";

I took my attention with KB971513 patch but that would not fit to win10. Specially, on another win10 machine, that works well and didn't pop-up any error hint.

I guess there is something incompatible with UIAutomationClient.dll but have no idea to fix it;
If you are free please have a look at it.
Thanks.

**Comment by yinkaisheng** [comment]
Maybe some other dlls that UIAutomationClientX86.dll depends are not found. UIAutomationClientX86.dll was compiled by Visual Studo 2010 sp1.
Try to install [Microsoft Visual C++ 2010 SP1 Redistributable Package (x86)](https://www.microsoft.com/en-us/download/confirmation.aspx?id=8328) or [x64](https://www.microsoft.com/en-us/download/details.aspx?id=13523)
If the problem still exists after installing the package, open UIAutomationClientx86.dll with [Dependency Walker](http://www.dependencywalker.com/), it will show the missed dlls that UIAutomationClientx86.dll depends.

**Comment by Kunkka1988** [comment]
It's very timely and I'll try to figure it out.
Thanks a lot.

**Comment by yinkaisheng** [comment]
Is it fixed?

**Comment by Kunkka1988** [comment]
It's not yet.
The analysis of Dependency Walker showed me there is some differences about API-MS-WIN-CORE*.dll/MSVCRT/MSVCP_WIN, but that was not obviously;
So I wanted to replace the DLLs from another machine but OS stopped me with permissions;

**Comment by Kunkka1988** [comment]
That's caused by OS version.
If change to pure OS then it will be fine.
Thanks.

**Comment by LeeseHe** [comment]
Hi Kunkka,

Whan do you mean when you say pure OS?

Thank you.

**Comment by Kunkka1988** [comment]
Hi Kaisheng,

Pure OS comes from MicroSoft, and there isn't any preloaded drivers/plugins/programs in it.
That means some driver/programs will change or affect the DLLs which uiautomation depends.
Thanks.

**Comment by yinkaisheng** [comment]
Build your UIAutomationClientX86.dll on the machine that failed
https://github.com/yinkaisheng/UIAutomationClient

**Comment by Kunkka1988** [comment]
Hi Kaisheng,

Got it, thanks.

**Comment by yinkaisheng** [comment]
I have recompiled the dlls to fit different python versions.
Update uiautomation by 'pip install -U uiautomation' and try again.

**Comment by yinkaisheng** [comment]
Please update the code and test again. I fixed a issue with 64 bit Python.
It should work now.

**Comment by yinkaisheng** [comment]
Please update the code and test again. I fixed a issue with 64 bit Python.
