### ISSUE TITLE
Is it possible to get html dom element or xpath

### ISSUE THREAD

**Issue by sartajg** [yinkaisheng/Python-UIAutomation-for-Windows#162]
Hi @yinkaisheng, I am able to get clicked text or checkbox or any other valve, but along with it I need html or xpath to the element. Is it possible to get that using this library. 
I know there is a way using selenium but I don't want to use.

**Comment by yinkaisheng** [comment]
uiautomation can't get dom element or xpath.

**Comment by sartajg** [comment]
Thanks. closing the ticket.
