### ISSUE TITLE
[Request] UI Automation with remote server

### ISSUE THREAD

**Issue by nguyenvanhuy0612** [yinkaisheng/Python-UIAutomation-for-Windows#163]
Hi yinkaisheng,
Thanks for attention.

I am working perfectly in my local computer, but I have some windows 10 clients. I want to automate some window applications in those clients.
To my knowledge your library is working with UIAutomationClient designed by Micsrosoft dev.

I wonder if I can run my code remotely in another server? Like WinDriverApp and appium did.
I don't use WinDriverApp and appium is because it's a lot more limited than your library.

I wonder if it is possible to run UIAutomationClient.dll on another client and my python code can connect to UIAutomationClient.dll to control applications on it.

Thanks in advance.
Huy Nguyen

**Comment by yinkaisheng** [comment]
As far as I know it is not supported in current API.
There is a new project https://github.com/microsoft/Microsoft-UI-UIAutomation that is upcoming.
It seems that it supports, but I have't tried. I haven't tried WinDriverApp and appium either.

**Comment by nguyenvanhuy0612** [comment]
Hi, 
Thanks for reply.
I respectfully wait in the hope that you will develop it for the remote windows client system.
This will be the best thing ever for me.
I don't know what you will do next, but with what you do I will think about you support Microsoft-UI-UIAutomation in the ele future.
Hope for it.
