### ISSUE TITLE
What's the system version when you run on Windows 10

### ISSUE THREAD

**Issue by LeeseHe** [yinkaisheng/Python-UIAutomation-for-Windows#17]
Hi Kaisheng,

In win10, I keep seeing access violation reading error. Seems it's still related to dll. What' your Windows 10 version?

Thank you.

**Comment by yinkaisheng** [comment]
My Windows 10 version is Windows 10 Enterprise, Version 1607 (Updated Jul 2016) (x64)
https://technet.microsoft.com/en-us/itpro/windows/whats-new/whats-new-windows-10-version-1607

**Comment by yinkaisheng** [comment]
I have recompiled the dlls to fit different python versions.
Update uiautomation by 'pip install -U uiautomation' and try again.

**Comment by vijaysaimutyala** [comment]
@LeeseHe Were you able to solve this?

**Comment by CaleGlisson** [comment]
Having this issue on two out of three machines. Trying to figure out what the difference is in the one that's currently working

**Comment by CaleGlisson** [comment]
Looks like the issue exists when using Python 3.6.1 64bit, but not Python 3.6.1 32bit

**Comment by yinkaisheng** [comment]
uiautomation has problems with 64 bit python. 
My dll returns uint64 values to python, but python truncates the values to 32 bit.
I need some time fo fix it.

**Comment by yinkaisheng** [comment]
Please update the code and test again. I fixed the issue with 64 bit Python.
It should work now.

**Comment by yinkaisheng** [comment]
I tested uiautomation with https://repo.anaconda.com/archive/Anaconda3-2018.12-Windows-x86_64.exe on 64 bit Windows 10. Python version is 3.7.1 64 bit.
The scripts in demos worked without errors.

**Comment by yinkaisheng** [comment]
Latest uiautomation 2.0 can be run without dlls.
