### ISSUE TITLE
读取QQ聊天记录不完整的问题

### ISSUE THREAD

**Issue by fetchniches** [yinkaisheng/Python-UIAutomation-for-Windows#174]
使用如下代码测试，鼠标放置在QQ群聊中某个人发送的消息，但最后返回的信息只是从QQ已经加载好的记录开始，到一定记录数后就没了，导致只能显示之前的记录，但我需要最新的消息。
而之后的记录即使通过`uiautomation.py -t 3` 显示也是读不到，也就是最新的那一部分消息接收不到。只有在我直接输出光标处的`Name`属性才有。
```
import uiautomation as auto


msg = auto.ControlFromCursor()
for item in msg.GetParentControl().GetChildren():
    print(item.Name)
```

**Comment by yinkaisheng** [comment]
微软Inspect.exe 也不能获取全部记录，也获取不到记录的坐标BoundingRectangle，应该是QQ内部UIAutomation Provider实现有问题，无法解决，除非QQ修改支持。

**Comment by fetchniches** [comment]
好的，多谢

**Comment by xjw666666** [comment]
> 好的，多谢

大佬，我也遇到了同样的问题，用uiautomation只能获得当前qq聊天的前几段聊天记录，新的那些记录获取不到，有解决方法了吗，或者有什么其他代替的库吗
