### ISSUE TITLE
【win10环境】导入此库后，获取不到缩放后的分辨率，怎么设置win缩放，125%、150%。得到的都是原始分辨率

### ISSUE THREAD

**Issue by justyyl** [yinkaisheng/Python-UIAutomation-for-Windows#179]
import ctypes
    import uiautomation as auto
    user32 = ctypes.windll.user32
    gdi32 = ctypes.windll.gdi32
    dc = user32.GetDC(None)
    widthScale = gdi32.GetDeviceCaps(dc, 8)  # 分辨率缩放后的宽度
    heightScale = gdi32.GetDeviceCaps(dc, 10)  # 分辨率缩放后的高度
    width = gdi32.GetDeviceCaps(dc, 118)  # 原始分辨率的宽度
    height = gdi32.GetDeviceCaps(dc, 117)  # 原始分辨率的高度
    scale = width / widthScale
    print(widthScale, heightScale, width, height, scale)
【win10环境】导入此库后，获取不到缩放后的分辨率，怎么设置win缩放，125%、150%。得到的都是原始分辨率

**Comment by yinkaisheng** [comment]
是预期行为，因为自动化鼠标位置等操作需要用缩放前的原始分辨率。uiautomation内部调用了系统API SetProcessDpiAwareness, 会使相关API获取的坐标都是缩放前的原始分辨率。
你要获取缩放后的分辨率，需要把import uiautomation放到你的函数后面。

**Comment by justyyl** [comment]
谢谢答复，目前是放在后面的。 不过，如果程序运行中改变了缩放，就不能即时获取相应缩放了。不知道有没有解决办法。

**Comment by yinkaisheng** [comment]
可以解决。
不过需要修改uiautomation源码，把SetProcessDpiAwareness(ProcessDpiAwareness.PerMonitorDpiAware) 这行代码注释掉。
默认获取的都是缩放后的分辨率坐标。
如果需要获取缩放前的原始分辨率坐标，在线程中单独调用下面代码，只有此线程获取的坐标是原始分辨率坐标。
自己控制是否需要原始分辨率。
```python
auto.SetThreadDpiAwarenessContext(auto.DpiAwarenessContext.PerMonitorAware)
```

一个例子，每次更改DPI，都能获取到最新的缩放坐标：
```python
#!python3
# -*- coding: utf-8 -*-
import os
import sys
import time
import threading
import uiautomation as auto


def threadFunc():
    th = threading.currentThread()
    auto.Logger.WriteLine('\nThis is running in a new thread. {} {}'.format(th.ident, th.name), auto.ConsoleColor.Cyan)
    auto.SetThreadDpiAwarenessContext(auto.DpiAwarenessContext.PerMonitorAware)
    with auto.UIAutomationInitializerInThread(debug=True):
        root = auto.GetRootControl()
        print('new thread, desktop rect:', root.BoundingRectangle)
        print('new thread, monitors rect:', auto.GetMonitorsRect())
    auto.Logger.WriteLine('\nThread exits. {} {}'.format(th.ident, th.name), auto.ConsoleColor.Cyan)


def main():
    mth = threading.currentThread()
    auto.Logger.WriteLine('This is running in main thread. {} {}'.format(mth.ident, mth.name), auto.ConsoleColor.Cyan)
    while True:
        root = auto.GetRootControl()
        print('main thread, desktop rect', root.BoundingRectangle)
        print('main thread, monitors rect:', auto.GetMonitorsRect())
        th = threading.Thread(target=threadFunc)
        th.start()
        th.join()
        input('\nplease change system DPI')


if __name__ == '__main__':
    main()
```

**Comment by justyyl** [comment]
感谢详尽答复。
