### ISSUE TITLE
Cannot run on Win10(works well on Win8.1)

### ISSUE THREAD

**Issue by LeiYangGH** [yinkaisheng/Python-UIAutomation-for-Windows#18]
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\yanglei2\Desktop\Python-UIAutomation-for-Windows-master\automation_notepad_py3.py 
Traceback (most recent call last):
  File "C:\Users\yanglei2\Desktop\Python-UIAutomation-for-Windows-master\automation_notepad_py3.py", line 7, in <module>
    import uiautomation as automation
  File "C:\Users\yanglei2\Desktop\Python-UIAutomation-for-Windows-master\uiautomation.py", line 55, in <module>
    _automationClient = _AutomationClient()
  File "C:\Users\yanglei2\Desktop\Python-UIAutomation-for-Windows-master\uiautomation.py", line 43, in __init__
    self.dll = ctypes.cdll.UIAutomationClientX86
  File "C:\Users\yanglei2\AppData\Local\Programs\Python\Python35-32\lib\ctypes\__init__.py", line 417, in __getattr__
    dll = self._dlltype(name)
  File "C:\Users\yanglei2\AppData\Local\Programs\Python\Python35-32\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
>>>

**Comment by yinkaisheng** [comment]
I have recompiled the dlls to fit different python versions.
Update uiautomation by 'pip install -U uiautomation' and try again.

**Comment by LeiYangGH** [comment]
I updated but same issue. can you have a look at my screen capture?
![windows10x64-2017-07-05-09-36-31](https://user-images.githubusercontent.com/5386998/27845887-90c22d66-6165-11e7-848c-6e90705dde40.png)

**Comment by yinkaisheng** [comment]
You updated by pip, pip installed the module to dir c:\...\Python35-32\Python34\Lib\site-packages\
But the code in your dir c:\sdk\python-ui...msater\ is not lastest. Update it please.
You ran automation_notepad_py3.py, the script loaded uiautomation in the dir c:\sdk\python-ui..., not the one in site-packages

**Comment by LeiYangGH** [comment]
Hi,
   After downloading the latest source code, I can successfully run the automation_notepad_py3.py now(only by command line, if use idle then errors do you know why?).
  Then I tried automation_calculator.py, it luanched calculator but did nothing then exception printed(command line and idle are same error). Can you have a look?
![windows10x64-2017-07-11-16-52-56](https://user-images.githubusercontent.com/5386998/28060502-e19bda0e-6659-11e7-85e3-bb48b650afa3.png)

**Comment by yinkaisheng** [comment]
what's the error in idle?
Yes, it is. Calc's UI changed in Windows 10.

**Comment by LeiYangGH** [comment]
Will you also write some scripts for Win10? Since in your homepage you said 'Support UIAutomation for MFC, WindowsForm, WPF, **Modern UI(Metro UI)**'

**Comment by yinkaisheng** [comment]
It works on Windows 10 now.
