### ISSUE TITLE
Configurable Logs Request

### ISSUE THREAD

**Issue by dan-vk** [yinkaisheng/Python-UIAutomation-for-Windows#182]
Hi, I noticed while using uiautomation navigation such as WalkControl, or a combination of Control functions, there are verbose log messages that I was not sure how to disable or change the debug levels of. Would it be possible to have the capability to modify the level of logs that are reported, or turn them off? Thanks in advance for any help.

Example Messages:

> 021-11-09 12:38:24.991 windows.py[323] find_controls -> Find Control Timeout: {RegexName: 'Error', ControlType: WindowControl}
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811cb0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811ef0 at 1841bdc2740>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811cb0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a8134e0 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811c20 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a813690 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812f40 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812910 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812910 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812f40 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812910 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811c20 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a8134e0 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812910 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812910 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811c20 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a8137b0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811ef0 at 1841bdc2740>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811cb0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812910 at 1841bdc2740>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812910 at 1841bdc2740>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a813720 at 1841bdc2740>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a813690 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812910 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811c20 at 1841bdc2740>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811cb0 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2740>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812b50 at 1841bdc26c0>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2840>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a813690 at 1841bdc26c0>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a8134e0 at 1841bdc26c0>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812b50 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811e60 at 1841bdc26c0>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811cb0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a8130f0 at 1841bdc26c0>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812b50 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812be0 at 1841bdc26c0>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a8134e0 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a811cb0 at 1841bdc26c0>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a813690 at 1841bdc2540>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a812b50 at 1841bdc26c0>
> Release <POINTER(IUIAutomationElement) ptr=0x1841a813690 at 1841bdc2540>

**Comment by yinkaisheng** [comment]
Only the first line "... Find Control Timeout: ..." was printed by uiautomation, others were not.
It seems that they were printed by module comtypes. 
But I have never seen the log "Release  <POINTER(IUIAutomationElement) ..." on my PC.

D:\Python38\Lib\site-packages\comtypes\__init__.py Line 911  _debug("Release %s", self)
```python
class _compointer_base(c_void_p, metaclass=_compointer_meta):
    "base class for COM interface pointer classes"
    def __del__(self, _debug=logger.debug):
        "Release the COM refcount we own."
        if self:
            # comtypes calls CoUnititialize() when the atexit handlers
            # runs.  CoUninitialize() cleans up the COM objects that
            # are still alive. Python COM pointers may still be
            # present but we can no longer call Release() on them -
            # this may give a protection fault.  So we need the
            # _com_shutting_down flag.
            #
            if not type(self)._com_shutting_down:
                _debug("Release %s", self)
                self.Release()
```

**Comment by dan-vk** [comment]
Awesome, thanks a lot for the pointer! Managed to mute the logs, attaching it here for reference if anyone else runs into this too.

https://docs.python.org/3/library/logging.html
comtypelogger = logging.getLogger("comtypes")  # This obtains the logging object for comtypes
comtypelogger.propagate = False  # This prevents debugging messages from being passed higher if I'm not looking for them
