### ISSUE TITLE
Call function "CaptureToImage" failed on python 3.10

### ISSUE THREAD

**Issue by xiaohuihui093** [yinkaisheng/Python-UIAutomation-for-Windows#187]
Call function "CaptureToImage" failed on python 3.10 for '3.10' >='3.8' is False.

![image](https://user-images.githubusercontent.com/44687807/146340217-7f81bde3-8332-4f6b-ac3a-925330b85e10.png)

**Comment by yinkaisheng** [comment]
fixed.
