### ISSUE TITLE
同个UI中有兩相同的Control

### ISSUE THREAD

**Issue by william4792** [yinkaisheng/Python-UIAutomation-for-Windows#19]
你好,剛接觸到自動測試領域,還在摸索中,看到你的代碼對我很有幫助
有碰到幾個問題想請問下:
當同個UI頁面有兩相通的控件類型,除了Rect位置不一樣,其餘信息完全相同,該如何選定正確的控件進行控制?
(例如:一頁面有兩ScrollBarControl
ControlType: ScrollBarControl    ClassName:     AutomationId: NonClientVerticalScrollBar    Rect: (176, 193, 193, 715)    Name: 垂直滚动条    Handle: 0x0(0)    Depth: 7    ProcessId:7828    RangeValue: 0

ControlType: ScrollBarControl    ClassName: LineVScrollBar    AutomationId: VerticalScrollBar    Rect: (1349, 193, 1366, 715)    Name: 垂直滚动条    Handle: 0x410A5A(4262490)    Depth: 7    ProcessId:7828    RangeValue: 0)
謝謝!

**Comment by william4792** [comment]
可遍歷所有控件,查找是否存在,存在者標Index編號區別
感謝

**Comment by yinkaisheng** [comment]
也可以用scrollbar = uiautomation.ScrollBarControl(... foundIndex= 2), 找到第二个ScrollBarControl

**Comment by william4792** [comment]
謝謝您的回覆!
想再請問下碰上被PaneControl包裹住的控件(只查的到PaneControl的信息)該怎麼做?
[例如您範例QQ中,ListItemControl是被包裹在PaneControl裏頭,可以偵測的到;但許多軟件偵測控件時,卻只能偵測到控件所在的PaneControl位置,該如何深入對單一控件操作?]

**Comment by yinkaisheng** [comment]
这种情况获取不到，没有办法获取。
有很多软件是用DirectUI开发的，不是用微软提供的GUI开发框架开发的。
大多数的DirectUI都不支持UIAutomation，只有很少量的DirectUI支持UIAutomation，比如QQ，Firefox，Qt 
如果要让DirectUI程序支持UIAutomation，DirectUI程序的作者必须实现UI Automation Provider，
DirectUI程序实现了UI Automation Provider，才能支持UIAutomation。

https://msdn.microsoft.com/en-us/library/windows/desktop/ee671597(v=vs.85).aspx

If your application includes any custom controls, you need to implement UI Automation providers for those controls to make them accessible to accessibility client applications. You also need to implement providers for any third party controls that do not include a provider. You implement a provider by implementing UI Automation provider interfaces and control pattern interfaces.
