### ISSUE TITLE
请问该如何获取窗口全部菜单项，包括子菜单？

### ISSUE THREAD

**Issue by jiliguluss** [yinkaisheng/Python-UIAutomation-for-Windows#190]
比如记事本程序，现在通过MenuBarControl获取菜单栏，调用GetChildren方法获取菜单项MenuItemControl：文件、编辑、格式、查看、帮助。现在想继续获取这些菜单的子菜单项，但是继续调用GetChildren方法得到的是空。正确的处理办法是什么呢？

**Comment by yinkaisheng** [comment]
需要菜单弹出来显示才能获取，没显示的话获取不到。
