### ISSUE TITLE
请问  该如何向密码控件发送文本

### ISSUE THREAD

**Issue by rejii0042** [yinkaisheng/Python-UIAutomation-for-Windows#191]
![image](https://user-images.githubusercontent.com/81682395/150284877-f90e3dc0-4519-4027-96f0-d4c52c44e4f2.png)
**发现如果向 这种控件 SendKeys 发送文本的话将会无效，请问该如何解决？**

**Comment by rejii0042** [comment]
@yinkaisheng

**Comment by yinkaisheng** [comment]
参考这个 #72

**Comment by rejii0042** [comment]
你好，参考该方式还是无法键入值
尝试采用 uiautomation.SendKey(int)方式，以及uiautomation.SendKeys(str,charMode=False)方式都无效

**Comment by rejii0042** [comment]
操作的是邮政储蓄银行

**Comment by yinkaisheng** [comment]
密码安全控件可能不支持，可能是故意做成不让自动化输入的，如果不支持，我也没有办法。

**Comment by shawnwangwang8** [comment]
同问，民生银行的密码输入框，也不支持输入，该如何处理？
