### ISSUE TITLE
Expand() method not work in class ComboBoxControl as report "ExpandCollapsePattern not supported"

### ISSUE THREAD

**Issue by yywudi** [yinkaisheng/Python-UIAutomation-for-Windows#2]
while I want to choose a value from a combobox, in my .net application, I found the "IsExpandCollapsePatternAvailable" value in the Inspect was "false".
so while I run 
`automation.ComboBoxControl(searchFromControl=blablabla, ClassName=‘blablabla').Select(value)`
it failed as in class ComboBoxControl(), method Select(), the code is `self.Expand()`.

and I just make a workaround that replace `self.Expand()` with `self.Click()`, and it works

later, I tried to not break your original code, so add an "if" in Select() method:

>         if self.IsExpandCollapsePatternAvailable():
            self.Expand()
        else:
            self.Click()

and add one property to get the IsExpandCollapsePatternAvailable value
>     def IsExpandCollapsePatternAvailable(self):
        '''Return bool'''
        return _automationClient.dll.GetElementIsExpandCollapsePatternAvailable(self.Element)

but it reports not found error

>    if self.IsExpandCollapsePatternAvailable():
  File "D:\Tools\Python\Python-UIAutomation-for-Windows\automation.py", line 1585, in IsExpandCollapsePatternAvailable
    return _automationClient.dll.GetElementIsExpandCollapsePatternAvailable(self.Element)
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'GetElementIsExpandCollapsePatternAvailable' not found

how do I know the functions detail in the _automationClient.dll ?

**Comment by yinkaisheng** [comment]
_automationClient.dll has a function GetElementPattern which can check whether a Pattern is available.

`def IsExpandCollapsePatternAvailable(self):
        '''return bool'''
        return _automationClient.dll.GetElementPattern(self.Element, PatternId.UIA_ExpandCollapsePatternId) != 0`

please get the latest code.
