### ISSUE TITLE
Any workaround for running 2 apps on one machine with multiple monitors ?

### ISSUE THREAD

**Issue by longk15t** [yinkaisheng/Python-UIAutomation-for-Windows#20]
I'm on a budget I cannot buy more machine, I just have 2 monitors and one machine. I have 2 Windows apps and need to run both in parallel, could I achieve run each app on each monitor by using your library at same time ?

**Comment by yinkaisheng** [comment]
try this:

`
#!python3
# -*- coding: utf-8 -*-
import os
import sys
import time
import multiprocessing
import uiautomation as automation

LastRecv = ''

def WaitFor(pipe, sec = 1):
    global LastRecv
    pipe.send('I wait, You continue')
    time.sleep(sec)
    if LastRecv != 'exit':
        LastRecv = pipe.recv()

def AutomateApp1(pipe):
    print('run app1')
    steps = 10
    print('find app1, move app1 to monitor 1, now do the following {} steps'.format(steps))
    WaitFor(pipe)
    for i in range(steps):
        print('app1 do step {}, wait 1 second'.format(i + 1))
        WaitFor(pipe)
    pipe.send('exit')

def AutomateApp2(pipe):
    print('run app2')
    steps = 15
    print('find app2, move app2 to monitor 2, now do the following {} steps'.format(steps))
    WaitFor(pipe)
    for i in range(steps):
        print('app2 do step {}, wait 1 second'.format(i + 1))
        WaitFor(pipe)
    pipe.send('exit')

def main():
    con1, con2 = multiprocessing.Pipe()
    p1 = multiprocessing.Process(target = AutomateApp1, args = (con1, ))
    p2 = multiprocessing.Process(target = AutomateApp2, args = (con2, ))
    p1.start()
    p2.start()

if __name__ == '__main__':
    main()

`
AutomateApp1 and AutomateApp2 will be run in different processes.
When one waits, the other runs.
The output:
run app1
find app1, move app1 to monitor 1, now do the following 10 steps
run app2
find app2, move app2 to monitor 2, now do the following 15 steps
app1 do step 1, wait 1 second
app2 do step 1, wait 1 second
app1 do step 2, wait 1 second
app2 do step 2, wait 1 second
app1 do step 3, wait 1 second
app2 do step 3, wait 1 second
app1 do step 4, wait 1 second
app2 do step 4, wait 1 second
app1 do step 5, wait 1 second
app2 do step 5, wait 1 second
app1 do step 6, wait 1 second
app2 do step 6, wait 1 second
app1 do step 7, wait 1 second
app2 do step 7, wait 1 second
app1 do step 8, wait 1 second
app2 do step 8, wait 1 second
app1 do step 9, wait 1 second
app2 do step 9, wait 1 second
app1 do step 10, wait 1 second
app2 do step 10, wait 1 second
app2 do step 11, wait 1 second
app2 do step 12, wait 1 second
app2 do step 13, wait 1 second
app2 do step 14, wait 1 second
app2 do step 15, wait 1 second

Does it fit you requeirement?

**Comment by longk15t** [comment]
I need to test this but really thanks for your help, but is this using python 3 ? how about in python 2 ?

**Comment by longk15t** [comment]
Could app1 and app2 be the same app but just two instances ?

**Comment by yinkaisheng** [comment]
It supports python 2.
The two app can be the same app.

**Comment by yinkaisheng** [comment]
Sorry, the code does not work, I need some time to fix it.

**Comment by longk15t** [comment]
Thanks man, need an amount of time to test this.

**Comment by longk15t** [comment]
Sorry for dumb question but when to use `SendAndWait()`, when to use `Wait()` ?

**Comment by yinkaisheng** [comment]
only one function uses Wait and call it just once at the beginng of the function.
call SendAndWait elsewhere and can not call Wait again
