### ISSUE TITLE
WalkControl使用的算法是深度优先搜索，而不是广度优先搜索

### ISSUE THREAD

**Issue by discovery-131794** [yinkaisheng/Python-UIAutomation-for-Windows#203]

**Comment by tdRPA** [comment]
是的，用广度优先会更好些，兄弟你后来怎么处理的？ @discovery-131794

**Comment by discovery-131794** [comment]
> 是的，用广度优先会更好些，兄弟你后来怎么处理的？ @discovery-131794
在指定深度的情况下，深度优先会更快，因为能跳过更多元素

**Comment by tdRPA** [comment]
邮件已收到，通常我在1～2天内回复。如有急事，请直接电话联系 ----我的微信 haijun-data

**Comment by discovery-131794** [comment]
@tdRPA 
在指定深度的情况下，如果查找的元素在偏左侧的节点，深度优先可以跳过不必要查找的元素，会更快一些。

**Comment by discovery-131794** [comment]
Hi @yinkaisheng ,
I developed a GUI tool to display UI tree structure which is more intuitive than command line.
https://github.com/discovery-131794/UI-Inspector
