### ISSUE TITLE
你好， 支持微信pc客户端吗？ 貌似不行。

### ISSUE THREAD

**Issue by dingdong7580** [yinkaisheng/Python-UIAutomation-for-Windows#21]
2017-06-23 04:03:28.451 Function: main, Line: 4207 -> Starts, Current Cursor Position: (867, 465)
ControlType: WindowControl    ClassName: ChatWnd    AutomationId:     Rect: (1084, 22, 1909, 982)    Name: test1    Handle: 0xF2394(992148)    Depth: 0
    ControlType: PaneControl    ClassName: popupshadow    AutomationId:     Rect: (1065, 3, 1928, 1001)    Name:     Handle: 0x72362(467810)    Depth: 1
    ControlType: PaneControl    ClassName: ChatContactMenu    AutomationId:     Rect: (-10000, -10000, -9999, -9999)    Name: ChatContactMenu    Handle: 0x82348(533320)    Depth: 1
        ControlType: PaneControl    ClassName: popupshadow    AutomationId:     Rect: (-10019, -10019, -9980, -9980)    Name:     Handle: 0x62396(402326)    Depth: 2
2017-06-23 04:03:28.484 Function: main, Line: 4238 -> Ends

**Comment by yinkaisheng** [comment]
是微信不支持UIAutomation, UIAutomation出现的时间比微信早，微信使用的界面库没有实现UIAutomation Provider,

**Comment by sytpb** [comment]
不支持，上面这不打印出信息了吗
