### ISSUE TITLE
How to get `Control` instance from `hwnd`?

### ISSUE THREAD

**Issue by Lx** [yinkaisheng/Python-UIAutomation-for-Windows#216]
Hello,

Many thanks for your efforts on `uiautomation`.

How to get a `Control` instance for a specific `hwnd`?  I've tried the following:

```py
>>> WindowControl(Handle=196796).Name
'<wrong title>'
>>> WindowControl(HandleId=196796).Name
'<wrong title>'
>>> WindowControl(Hwnd=196796).Name
'<wrong title>'
>>> WindowControl(hwnd=196796).Name
'<wrong title>'
>>> WindowControl(WindowHandle=196796).Name
'<wrong title>'
>>> WindowControl(NativeHandle=196796).Name
'<wrong title>'
>>> WindowControl(NativeWindowHandle=196796).Name
'<wrong title>'
>>> WindowControl(NativeWindowHandleId=196796).Name
'<wrong title>'
>>> WindowControl(NativeWindowId=196796).Name
'<wrong title>'
```

I found reference to `NativeWindowHandleProperty` in the source but I couldn't understand.

Is there documentation for the complete list of search properties?

**Comment by Lx** [comment]
Actually, sorry, I see this in the README about search properties:

> the following parameters can be used
> searchFromControl = None,
> searchDepth = 0xFFFFFFFF,
> searchInterval = SEARCH_INTERVAL,
> foundIndex = 1
> Name
> SubName
> RegexName
> ClassName
> AutomationId
> ControlType
> Depth
> Compare

Does this unfortunately mean searching by `hwnd` is impossible?

**Comment by yinkaisheng** [comment]
use ControlFromHandle

**Comment by Lx** [comment]
It is so simple! Thank you!
