### ISSUE TITLE
请问怎么获得combox当前选中项的文本

### ISSUE THREAD

**Issue by NecEvils** [yinkaisheng/Python-UIAutomation-for-Windows#233]
查看combox控件，只有selection里面保存了选中项的名字，请问要怎么获取？
![1](https://user-images.githubusercontent.com/23426419/216737214-45fc5a4c-60fc-4f6f-b4a0-043737bd9d9b.jpeg)

**Comment by yinkaisheng** [comment]
valuePt = combo.GetValuePattern()
    if valuePt:
        print('current selection:', valuePt.Value)
    selectPt = combo.GetSelectionPattern()
    if selectPt:
        print('current selection:', selectPt.GetSelection())
