### ISSUE TITLE
Get list of elements by Name/RegexName

### ISSUE THREAD

**Issue by Loocos** [yinkaisheng/Python-UIAutomation-for-Windows#244]
Hi,

Thank you yinkaisheng for this library. 

I would want to know if there's a way to get a list of elements by name/regex.
In my case, I've multiple elements with the same name. And I want to target the second one. Or currently, it focus on the first found. 

Is there an existing way to do this ?

Thanks in advance

**Comment by qq463505965** [comment]
first found.GetNextSiblingControl() # navigate to the next one
