### ISSUE TITLE
The SetTopmost method does not work as expected always.

### ISSUE THREAD

**Issue by itigoo** [yinkaisheng/Python-UIAutomation-for-Windows#25]
Hello yinkaisheng,
This project is fantastic and I think it could really repalce the QTP. However, I found the SetTopmost method not always work as expected when running the demo of notepadtop.py. Here are the reproducing steps:
1. Open a notepad and minimize it.
2. Run notepadtop.py.

the definition of SetWindowTopmost(hWnd, isTopmost) is:
topValue = SWP.HWND_TOPMOST if isTopmost else SWP.HWND_NOTOPMOST
        return Win32API.SetWindowPos(hWnd, topValue, 0, 0, 0, 0, SWP.SWP_NOSIZE|SWP.SWP_NOMOVE)

I think it's better to change to:
topValue = ShowWindow.Restore if isTopmost else ShowWindow.Hide
        Win32API.ShowWindow(hWnd, topValue)
        if isTopmost:
            Win32API.SetForegroundWindow(hWnd)

**Comment by yinkaisheng** [comment]
Hi itigoo
Topmost means that places the window above all non-topmost windows. The window maintains its topmost position even when it is deactivated.

When a topmost windows is shown, if you active another no topmost window, the topmost window still can cover the active no topmost window.

If a window was hidden or minimized, SetTopmost doesn't show the window. I follow the Win32 API SetWindowPos.

I updated notepadtop.py.

**Comment by itigoo** [comment]
OK, thanks.
