### ISSUE TITLE
Publish uiautomation as a conda package : requires pypi Source Distribution

### ISSUE THREAD

**Issue by rxm7706** [yinkaisheng/Python-UIAutomation-for-Windows#251]
I would like to use uiautomation - but need to use conda 
uiautomation on pypi does not include Source Distributions 
  - https://pypi.org/project/uiautomation/#files
If you publish the Source (targ.gz) in additional to the wheel file, I can help create a conda pacakge for uiautoamation on conda-forge that everyone can use.

**Comment by rxm7706** [comment]
@yinkaisheng FYI - https://anaconda.org/conda-forge/uiautomation

**Comment by yinkaisheng** [comment]
OK
