### ISSUE TITLE
Add source distribution to pypi - to create conda-forge package

### ISSUE THREAD

**Issue by rxm7706** [yinkaisheng/Python-UIAutomation-for-Windows#253]
Hello
There is no conda distribution of UIAutomation
The current pypi upload does not include Source Distributions 
https://pypi.org/project/uiautomation/#files

1. If the tar.gz source distribution is added, we can help create a conda-forge package 
2. This will help the community that uses conda-forge and help package rpaframework-windows and rpaframework which was used extensively in the conda ecosystem till uiautomation was added as a dependency 

Thanks and regards.

cc @millsks

**Comment by yinkaisheng** [comment]
uploaded
