### ISSUE TITLE
Win10系统下，多线程中控件获取不到

### ISSUE THREAD

**Issue by zhuangyuan1234** [yinkaisheng/Python-UIAutomation-for-Windows#26]
Win7系统下程序执行一切正常，放在Win10系统下程序就会卡住，调试后发现在多线程中控件获取不到，一直处于Connect的状态，比如这样一句代码：automation.WindowControl(searchDepth=1, AutomationId='***', Name=‘***')，不放在线程中执行可以获取到控件，一旦放在线程中执行这样一句代码程序就会卡住，一直处于Connect的状态，不知道是什么原因，请老师指教，谢谢！

**Comment by yinkaisheng** [comment]
不支持多线程，只能在一个线程中用

**Comment by zhuangyuan1234** [comment]
也就是说在Win7上支持，Win10上不支持？

**Comment by yinkaisheng** [comment]
都不支持，可能win7碰巧你的场景没出问题，其它场景可能就会有问题了。

**Comment by zhuangyuan1234** [comment]
回答好及时啊，老师，呵呵，谢谢！

**Comment by cuiyubing819** [comment]
胜哥，能不能出个中文帮助文档，也方便推广，万分感激

**Comment by yinkaisheng** [comment]
现在2.0版本支持多线程。
