### ISSUE TITLE
TextRange.ExpandToEnclosingUnit should take an argument

### ISSUE THREAD

**Issue by michaelmesser** [yinkaisheng/Python-UIAutomation-for-Windows#269]
https://github.com/yinkaisheng/Python-UIAutomation-for-Windows/blob/master/uiautomation/uiautomation.py#L5017
should take an argument to match
https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomationtextrange-expandtoenclosingunit

**Comment by yinkaisheng** [comment]
fixed
