### ISSUE TITLE
How to set speed of mouse movement with Click() function

### ISSUE THREAD

**Issue by ajkessel** [yinkaisheng/Python-UIAutomation-for-Windows#292]
Is there any way to globally set mouse speed to move faster? For example, if I have this code:
```
root = auto.GetRootControl()
taskbar = root.Control(searchDepth=1,Name='Taskbar')
tray = taskbar.Control(searchDepth=1, ClassName='TrayNotifyWnd')
overflow = tray.Control(searchDepth=1, Name='Notification Chevron')
overflow.Click(waitTime=1.0)
```
The mouse moves at a "normal" speed over to the notification chevron to click. I would like it to move faster or instantly if possible. But `Click()` does not take a move speed parameter. Is there a way to move faster?

**Comment by RichardWang2023** [comment]
Try `Click(simulateMove=False)`

**Comment by ajkessel** [comment]
That works great, thanks!

**Comment by RichardWang2023** [comment]
> That works great, thanks!
> 
> Maybe documentation could be clearer?

I usually test my code in `Jupyter Notebook` or `VScode`. When you input `Function_name(`, you can see all the params and docs, that might be helpful.
