### ISSUE TITLE
How to get the ExpandCollapseState?

### ISSUE THREAD

**Issue by yywudi** [yinkaisheng/Python-UIAutomation-for-Windows#3]
Hi
in your last commit, you update the ExpandCollapseState() class, and I can see this state value for a TreeItemControl in Inspect.exe, but is that any method to get this state?
I want to try to get all the TreeItemControls and loop calling Expand() until it's a LeafNode.

or shall I use walkTree() to get all of them?  I tried, but walkTree() will use getChildrenFunc/getFirstChildFunc/getNextSiblingFunc, but if the tree was not expanded, all are None.

**Comment by yywudi** [comment]
Try to add a function in `class ExpandCollapsePattern()`, copy from `CurrentToggleState()` in `class 
TogglePattern()` 

>     def CurrentExpandCollapseState(self):
        '''return ExpandCollapseState value'''
        pattern = _automationClient.dll.GetElementPattern(self.Element, PatternId.UIA_ExpandCollapsePatternId)
        if pattern:
            return _automationClient.dll.ExpandCollapsePatternGetExpandCollapseState(pattern)
            _automationClient.dll.ReleasePattern(pattern)
        else:
            Logger.WriteLine('ExpandCollapsePattern is not supported!', ConsoleColor.Yellow)

tried `return _automationClient.dll.ExpandCollapsePatternGetExpandCollapseState(pattern)`   
or `return _automationClient.dll.ExpandCollapsePatternCurrentExpandCollapseState(pattern)`   
or `return _automationClient.dll.ExpandCollapsePatternExpandCollapseState(pattern)`

all got replied 
>
  File "D:\xxx\automation.py", line 1903, in CurrentExpandCollapseState
    return _automationClient.dll.ExpandCollapsePatternGetExpandCollapseState(pattern)
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'ExpandCollapsePatternGetExpandCollapseState' not found


Is there any documents or open source code to check what kind of functions supported in `_automationClient.dll` .?

**Comment by yinkaisheng** [comment]
I added CurrentExpandCollapseState in class ExpandCollapsePattern.
You should use WalkTree if you want to get all TreeItems and expand the TreeItems that are collapsed.
Look at the script get_system_devices.py. It demonstrates how to iterate a TreeControl and expand the collapsed items.
_automationClient.dll is not open source.
