### ISSUE TITLE
Control.CaptureToImage(path) black screenshot UWP Apps

### ISSUE THREAD

**Issue by salihaMr** [yinkaisheng/Python-UIAutomation-for-Windows#33]
The CaptureToImage() method doesn't work with UWP application. It takes black screenshots. 
For "ApplicationFrameWindow" Class Name.

**---- Code ----** (Exp:)
`import uiautomation as uiauto
calculatorWindow = uiauto.WindowControl(Name="Calculator") # The UWP calculator app
calculatorWindow.CaptureToImage("d:\\captureCalculatorWindowControl.png")
`
**---- Result ----**
![capturecalculatorwindowcontrol](https://user-images.githubusercontent.com/18186232/40182903-c6167cd0-59ec-11e8-9c88-c974ef694107.png)

![capture](https://user-images.githubusercontent.com/18186232/40182925-d0c70168-59ec-11e8-803f-810be1635052.png)

**Comment by yinkaisheng** [comment]
I fixed it now.
On Windows 10, 7 pixels of window's left, right and bottom borders are transparent.
![default](https://user-images.githubusercontent.com/5846696/40302031-70d304fa-5d20-11e8-8623-1badac28b2a2.png)

`noteWindow = uiautomation.WindowControl(searchDepth = 1, ClassName = 'Notepad')
noteWindow.CaptureToImage('calc.png', 7, 0, -14, -7) #cut the borders`

**Comment by salihaMr** [comment]
Hi Yinkai Sheng, 
First of all, thank you for your replay. But think that you didn't understand my question.
The problem is not about Windows 10, ... . But it about UWP applications. 
the CaptureToImage() method works for any application except UWP apps (where ClassName=ApplicationFrameWindow ). 
In my example i used the UWP Calculator app.

I tested your code ( #cut the borders ) with a UWP app and it doesn't work. It takes black screenshot. 
Thanks,

**Comment by yinkaisheng** [comment]
Did you pull the latest code? I also updated uiautomation source code.

**Comment by salihaMr** [comment]
Thank you, it works
