### ISSUE TITLE
Controls visible but their BoundingRectangle are all 0 

### ISSUE THREAD

**Issue by salihaMr** [yinkaisheng/Python-UIAutomation-for-Windows#34]
Hi, 
Is that normal that you should do `time.Sleep(x)` so the BoundingRectangle of the control will be updated with the current values?
It wasn't the case before! 
Thanks,

**Comment by yinkaisheng** [comment]
It depends on the controls. Some controls maybe, some not.
I also found this problem when I wrote this module.
See the comment in uiautomation.py line 1910 Bitmap.FromControl.
![default](https://user-images.githubusercontent.com/5846696/40336260-3d77a996-5d9b-11e8-8971-816f32800d98.png)

I dont't know which control need to be sleeped.

**Comment by salihaMr** [comment]
Thank you for your replay,  I already saw the comment. 
But it wasn't the case . That's why i wrote the issue!
Just for ControlType = TextControl (But i'm not sure).

So there is nothing to do to fix that?

**Comment by yinkaisheng** [comment]
Yes
UIAutomation askes software's controls for their control information.
If controls don't give the right information, there is no way.
