### ISSUE TITLE
询问下如何获取窗口名称和控件名称

### ISSUE THREAD

**Issue by edwardguo0123** [yinkaisheng/Python-UIAutomation-for-Windows#35]
大神，   
      谢谢你的这套框架，有几个问题想问下：
      1. 如过我新安装了一个程序，比如可执行文件是"abc.exe"，我可以如何打开它
      2.如果这是一个.net写的程序，但是没有源代码，我要如何知道它某个窗口和控件的名字？
      3.如果程序不是.net写的，依然可以用这套框架吗？可以怎样知道窗口和控件的名字?

非常感谢了！！！

**Comment by yinkaisheng** [comment]
看看 https://www.cnblogs.com/Yinkaisheng/p/3444132.html

**Comment by edwardguo0123** [comment]
看到了，多谢了，大神！！！：）
