### ISSUE TITLE
一些场景无法解决的问题

### ISSUE THREAD

**Issue by solio** [yinkaisheng/Python-UIAutomation-for-Windows#5]
日志会再补上

场景1:利用windows任务计划执行，UI自动化的脚本无法执行，会报寻找控件超时的错误
场景2:利用time.sleep() 一段时间，当电脑锁屏后也无法执行UI自动化

有没有办法解决

**Comment by yinkaisheng** [comment]
场景1没明白，
场景2解决不了，是UI自动化的限制。

**Comment by 910387466** [comment]
This is the reply of the robot？


------------------ 原始邮件 ------------------
发件人: "yinkaisheng";<notifications@github.com>;
发送时间: 2016年6月28日(星期二) 中午11:53
收件人: "yinkaisheng/Python-UIAutomation-for-Windows"<Python-UIAutomation-for-Windows@noreply.github.com>; 

主题: Re: [yinkaisheng/Python-UIAutomation-for-Windows] 一些场景无法解决的问题 (#5)




Closed #5.
