### ISSUE TITLE
如何恢复最小化的窗口

### ISSUE THREAD

**Issue by Jonwing** [yinkaisheng/Python-UIAutomation-for-Windows#52]
我的使用场景是用脚本检测某个窗口是否在最前面，如果不在，就检查是否被最小化了，如果不是被最小化，就起一个新的窗口。如果已有窗口，就进行下一步活动。

现在我已经可以检查出窗口被最小化了，但没有办法调到最前面。
那个窗体是个Qt5的pannel

无论我用`panel.Show()` 还是 `panel.SetFocus()`还是一起使用都不能恢复窗体，请问是不是我的使用方法不对？

**Comment by yinkaisheng** [comment]
使用pip安装或git pull最新代码，调用PaneControl.SwitchToThisWindow或者PaneControl.SetActive，加了几个函数

**Comment by Jonwing** [comment]
感谢更新:pray:

**Comment by kayhu** [comment]
> 使用pip安装或git pull最新代码，调用PaneControl.SwitchToThisWindow或者PaneControl.SetActive，加了几个函数

你好，在程序运行前，窗口已经最小化到系统托盘图标，再启动程序，这时候好像SwitchToThisWindow和SetActive不起作用，这种如何处理

**Comment by lostrain** [comment]
我也遇到这个问题了，程序启动就默认最小化到托盘了，通过WindowControl去查找好像就找不到呢
