### ISSUE TITLE
你好，有这个项目的帮助文档吗？  

### ISSUE THREAD

**Issue by qdwangjianjun** [yinkaisheng/Python-UIAutomation-for-Windows#53]
http://www.cnblogs.com/Yinkaisheng/p/3444132.html  比较粗糙，有详细API文档吗？

**Comment by yinkaisheng** [comment]
没有

**Comment by qdwangjianjun** [comment]
你好，我在CMD中运行uiautomation.py -h，没有出现帮助信息，直接结束掉了。uiautomation.py -t3也不行。
操作系统为Win10，python为3.7
![image](https://user-images.githubusercontent.com/40756962/53550842-af9b1e80-3b72-11e9-88ab-5b41524f799d.png)

**Comment by qdwangjianjun** [comment]
> 没有

你好，我在CMD中运行uiautomation.py -h，没有出现帮助信息，直接结束掉了。uiautomation.py -t3也不行。
操作系统为Win10，python为3.7

**Comment by yinkaisheng** [comment]
要运行**e:\python3_32\Scripts\automation.py** -h
automation.py是另一个单独的脚本

**Comment by qdwangjianjun** [comment]
> 要运行**e:\python3_32\Scripts\automation.py** -h
> automation.py是另一个单独的脚本

谢谢，已经解决
