### ISSUE TITLE
consoleWindow = automation.GetConsoleWindow()  返回为None

### ISSUE THREAD

**Issue by qdwangjianjun** [yinkaisheng/Python-UIAutomation-for-Windows#55]
Python3.7  Win10操作系统，参考https://www.cnblogs.com/Yinkaisheng/p/3444132.html 对记事本进行操作，、consoleWindow = automation.GetConsoleWindow() 返回结果为None

**Comment by yinkaisheng** [comment]
在桌面创建一个cmd.exe的快捷方式，右击 以管理员权限运行，在cmd里再调用
python automation_notepad_py3.py
把项目主页的英文说明看一遍，里面都说明过了。
