### ISSUE TITLE
你好，想实现按下鼠标右键进行划线的功能，win32api里面好像不支持

### ISSUE THREAD

**Issue by qdwangjianjun** [yinkaisheng/Python-UIAutomation-for-Windows#64]

**Comment by yinkaisheng** [comment]
加了uiautomation.RightDragDrop

**Comment by qdwangjianjun** [comment]
你好，十分感谢，RightDragDrop 应该是只能右键画直线吧。如何画正方形？  最好分解下方法: 按下左键或者右键，移动鼠标。

**Comment by qdwangjianjun** [comment]
已经解决，通过pynput第三方库的mouse.press和mouse.release 解决该问题。再次感谢作者。

**Comment by qdwangjianjun** [comment]
个人觉得这个比pywinauto 好用多了，UI自动化强烈推荐

**Comment by yinkaisheng** [comment]
uiautomation使用 win32api mouse_event 函数实现 鼠标按下、释放、移动，没有封装单独的函数
