### ISSUE TITLE
使用uiautomation再使用pyautogui这个包会报错

### ISSUE THREAD

**Issue by JackyNiu** [yinkaisheng/Python-UIAutomation-for-Windows#65]
##示例代码

-------

`
import uiautomation
import pyautogui
import time
def WalkDesktop():
    def GetFirstChild(control):
        return control.GetFirstChildControl()

    def GetNextSibling(control):
        return control.GetNextSiblingControl()

    desktop = uiautomation.GetRootControl()
    for control, depth in uiautomation.WalkTree(desktop, getFirstChildFunc=GetFirstChild, getNextSiblingFunc=GetNextSibling, includeTop=True, maxDepth= 1):
        print(control.ClassName,control.Handle)

WalkDesktop()
del WalkDesktop
time.sleep(1)
pyautogui.click(100,200)
`
报错信息如下：
 File "D:\Python3.6\lib\site-packages\pyautogui-0.9.40-py3.5.egg\pyautogui\__init__.py", line 400, in click
  File "D:\Python3.6\lib\site-packages\pyautogui-0.9.40-py3.5.egg\pyautogui\__init__.py", line 1111, in _failSafeCheck
  File "D:\Python3.6\lib\site-packages\pyautogui-0.9.40-py3.5.egg\pyautogui\__init__.py", line 237, in position
  File "D:\Python3.6\lib\site-packages\pyautogui-0.9.40-py3.5.egg\pyautogui\_pyautogui_win.py", line 361, in _position
ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_Point instance instead of pointer to POINT

**Comment by yinkaisheng** [comment]
我没有用过pyautogui，我电脑上装pip install pyautogui失败了，你自己debug调试看看

Collecting pygetwindow (from pyautogui)
  Downloading https://files.pythonhosted.org/packages/01/ed/56d4a369c6e18f6b239d9ef37b3222ba308bfebf949571b2611ff7d64f1d/PyGetWindow-0.0.4.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\yks\AppData\Local\Temp\pip-install-18w4b0kl\pygetwindow\setup.py", line 11, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: illegal multibyte sequence
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\yks\AppData\Local\Temp\pip-install-18w4b0kl\pygetwindow\

**Comment by yinkaisheng** [comment]
我用另一个module的时候出现了类似的问题。
分析后发现是因为两个模块都用了ctypes调用了相同的系统函数。比如
我写了一个module1.py, 里面用ctypes调用了两个系统函数
```python
# -*- coding: utf-8 -*-
# module1.py
import ctypes
import ctypes.wintypes

class POINT(ctypes.Structure):
    _fields_ = [("x", ctypes.wintypes.LONG),
                ("y", ctypes.wintypes.LONG)]

ctypes.windll.user32.WindowFromPoint.argtypes = (POINT, )
ctypes.windll.user32.WindowFromPoint.restype = ctypes.c_void_p
ctypes.windll.user32.GetCursorPos.argtypes = (ctypes.POINTER(POINT), )

def WindowFromPoint(x, y):
    return ctypes.windll.user32.WindowFromPoint(POINT(x, y))

def GetCursorPos():
    point = POINT(0, 0)
    ctypes.windll.user32.GetCursorPos(ctypes.byref(point))
    return point.x, point.y
```
**把module1.py复制一份改名为module2.py**，这时有两个module1, module2, 它们的代码时完全一样的。
这时如果写个脚本test.py同时调用module1, module2就会出问题。
```python
# -*- coding:utf-8 -*-
# test.py
import module1
import module2

def main():
    print('module1')
    print('handle', module1.WindowFromPoint(100, 100))
    print('cursor', module1.GetCursorPos())

    print('module2')
    print('handle', module2.WindowFromPoint(100, 100))
    print('cursor', module2.GetCursorPos())

if __name__ == '__main__':
    main()
```
运行test.py就会报错：
ctypes.ArgumentError: argument 1: <class 'TypeError'>: **expected POINT instance instead of POINT**

import module1
import module2
导入两个模块后，WindowFromPoint和GetCursorPos的参数只有用module2.POINT才是合法的, module1的修改被module2覆盖掉了。
在test.py中，用module1调用时，传入的参数是module1.POINT，而不是module2.POINT,
类型不匹配，就会报错。

假设module1是一个人写的模块，module2是另一个人写的模块，他们的模块中恰好都用ctypes调用了类似的代码，如果同时用这两个模块，调用的时候就会出错了。

解决方法是：
不要修改argtypes，把module1, module2中的下面两行代码注释掉就不会出错了。
```
#ctypes.windll.user32.WindowFromPoint.argtypes = (POINT, )
ctypes.windll.user32.WindowFromPoint.restype = ctypes.c_void_p
#ctypes.windll.user32.GetCursorPos.argtypes = (ctypes.POINTER(POINT), )
```
我已经把我的代码uiautomation修改好了，如果还有问题，可能是其它的module中有类似的代码，你需要向其它的module作者提issue修改下，必须双方都修改才能解决。

**Comment by JackyNiu** [comment]
太谢谢老师了，

**Comment by JJJJShen** [comment]
> 我用另一个module的时候出现了类似的问题。
> 分析后发现是因为两个模块都用了ctypes调用了相同的系统函数。比如
> 我写了一个module1.py, 里面用ctypes调用了两个系统函数
> 
> ```python
> # -*- coding: utf-8 -*-
> # module1.py
> import ctypes
> import ctypes.wintypes
> 
> class POINT(ctypes.Structure):
>     _fields_ = [("x", ctypes.wintypes.LONG),
>                 ("y", ctypes.wintypes.LONG)]
> 
> ctypes.windll.user32.WindowFromPoint.argtypes = (POINT, )
> ctypes.windll.user32.WindowFromPoint.restype = ctypes.c_void_p
> ctypes.windll.user32.GetCursorPos.argtypes = (ctypes.POINTER(POINT), )
> 
> def WindowFromPoint(x, y):
>     return ctypes.windll.user32.WindowFromPoint(POINT(x, y))
> 
> def GetCursorPos():
>     point = POINT(0, 0)
>     ctypes.windll.user32.GetCursorPos(ctypes.byref(point))
>     return point.x, point.y
> ```
> 
> WindowFromPoint是系统user32.dll里的函数，
> WindowFromPoint.argtypes设置WindowFromPoint函数的参数类型。
> WindowFromPoint.restype设置WindowFromPoint函数的返回类型。
> **把module1.py复制一份改名为module2.py**，这时有两个module1, module2, 它们的代码时完全一样的。
> 这时如果写个脚本test.py同时调用module1, module2就会出问题。
> 
> ```python
> # -*- coding:utf-8 -*-
> # test.py
> import module1
> import module2
> 
> def main():
>     print('module1')
>     print('handle', module1.WindowFromPoint(100, 100))
>     print('cursor', module1.GetCursorPos())
> 
>     print('module2')
>     print('handle', module2.WindowFromPoint(100, 100))
>     print('cursor', module2.GetCursorPos())
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> 运行test.py就会报错：
> ctypes.ArgumentError: argument 1: <class 'TypeError'>: **expected POINT instance instead of POINT**
> 
> import module1
> import module2
> 导入两个模块后，WindowFromPoint和GetCursorPos的参数只有用module2.POINT才是合法的, module1的修改被module2覆盖掉了。
> 在test.py中，用module1调用时，传入的参数是module1.POINT，而不是module2.POINT,
> 类型不匹配，就会报错。
> 
> 假设module1是一个人写的模块，module2是另一个人写的模块，他们的模块中恰好都用ctypes调用了类似的代码，如果同时用这两个模块，调用的时候就会出错了。
> 
> 一般来说，如果argtypes中有结构体或指针类型，才会出错，如果都是整形的话，不会有这个错误。
> 
> 解决方法是：
> 不要修改argtypes，也是可以调用的，把module1, module2中的下面两行代码注释掉就不会出错了。
> 
> ```
> #ctypes.windll.user32.WindowFromPoint.argtypes = (POINT, )
> ctypes.windll.user32.WindowFromPoint.restype = ctypes.c_void_p
> #ctypes.windll.user32.GetCursorPos.argtypes = (ctypes.POINTER(POINT), )
> ```
> 
> 我已经把我的代码uiautomation修改好了，如果还有问题，可能是其它的module中有类似的代码，你需要向其它的module作者提issue修改下，必须双方都修改才能解决。

你好，我是同样的问题。但是不知道为什么 没有在automation和pyautogui中找到
```
#ctypes.windll.user32.WindowFromPoint.argtypes = (POINT, )
ctypes.windll.user32.WindowFromPoint.restype = ctypes.c_void_p
#ctypes.windll.user32.GetCursorPos.argtypes = (ctypes.POINTER(POINT), )
```
