### ISSUE TITLE
_ctypes.COMError: (-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))

### ISSUE THREAD

**Issue by ViolenceAesthetics** [yinkaisheng/Python-UIAutomation-for-Windows#66]
======================================================================
ERROR: test_Battle_net_binding_cancel (netease.testCase.homePage.DzclientHome.DzclientHome)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\netease\netease_AutoQtUi\netease\testCase\homePage\DzclientHome.py", line 18, in test_Battle_net_binding_cancel
    Dzclient_home_Windows = auto.ControlFromHandle(hwnd)
  File "D:\netease\netease_AutoQtUi\uiautomation\uiautomation.py", line 7468, in ControlFromHandle
    return Control.CreateControlFromElement(_AutomationClient.instance().IUIAutomation.ElementFromHandle(handle))
_ctypes.COMError: (-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))

----------------------------------------------------------------------
Ran 2 tests in 12.409s

FAILED (errors=1)

**Comment by yinkaisheng** [comment]
handle是无效的

**Comment by ViolenceAesthetics** [comment]
3Q 是这样的 已经解决
