### ISSUE TITLE
如何精准的控制滑块的滑动？

### ISSUE THREAD

**Issue by qdwangjianjun** [yinkaisheng/Python-UIAutomation-for-Windows#69]
大大，如何精准的控制滑块的滑动呢？ 不太想通过鼠标点击的方式实现。

**Comment by yinkaisheng** [comment]
demos\automation_devicemanager.py

treeScrollPattern = tree.GetScrollPattern()
treeScrollPattern.SetScrollPercent(auto.ScrollPattern.NoScrollValue, 0)
treeScrollPattern.SetScrollPercent(auto.ScrollPattern.NoScrollValue, 22.3)
treeScrollPattern.SetScrollPercent(auto.ScrollPattern.NoScrollValue, 100)
