### ISSUE TITLE
具体可以识别哪种类型的QT界面控件呢？能具体说明一下吗？不支持的QT控件有什么特征呢？

### ISSUE THREAD

**Issue by chuanyuny** [yinkaisheng/Python-UIAutomation-for-Windows#70]
如题，谢谢！

**Comment by yinkaisheng** [comment]
我也不知道具体有哪些，前年我只是在Qt老版本遇到过一个combobox弹出的下拉列表里不支持。
我没有测试过所有的Qt控件。
最新版的Qt我也没有测试过。

**Comment by chuanyuny** [comment]
能加一下微信吗？有一些具体的问题想咨询。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: kaisheng.yin <notifications@github.com>
发送时间: 2019年4月27日 11:24
收件人: yinkaisheng/Python-UIAutomation-for-Windows <Python-UIAutomation-for-Windows@noreply.github.com>
抄送: chuanyuny <704746345@qq.com>, Author <author@noreply.github.com>
主题: 回复：[yinkaisheng/Python-UIAutomation-for-Windows] 具体可以识别哪种类型的QT界面控件呢？能具体说明一下吗？不支持的QT控件有什么特征呢？ (#70)




我也不知道具体有哪些，前年我只是在Qt老版本遇到过一个combobox弹出的下拉列表里不支持。
 我没有测试过所有的Qt控件。
 最新版的Qt我也没有测试过。
