### ISSUE TITLE
quick find that there is no element

### ISSUE THREAD

**Issue by koroner1** [yinkaisheng/Python-UIAutomation-for-Windows#78]
Hello,

My question is about way of finding element or rather i want to check if element exists in one loop iteration.

for example:
```python
element = auto.WindowControl(searchDepth=1, ClassName="#32770", Name="Name", searchWaitTime=0.1)
element = element.ButtonControl(searchDepth=1, Name = 'No', searchWaitTime=0.1)
element.Click(simulateMove=False)
# element.Invoke() ?
```

As you may see before i set:

```python
searchWaitTime=0.1
```

so it should be fast, but if no element found then it takes much longer than 0.1 second
so for now i making like this:
```python
def ifDialogWindowExists():
    dekstopChildren = auto.GetRootControl().GetChildren()
    for desktopChild in dekstopChildren:
        if desktopChild.Name == 'DialogName' and desktopChild.ClassName == '#32770':
            element = auto.WindowControl(searchDepth=1, ClassName="#32770", Name="DialogName", searchWaitTime=0.1)
            element = element.ButtonControl(searchDepth=1, Name = 'No', searchWaitTime=0.1)
            element.Click(simulateMove=False)
```

Is already better way?

**Comment by yinkaisheng** [comment]
use Control.Exists.
I updated readme just now. Please read the following part:

uiautomation only starts to search the control when you first call a control's method or property that indirectly calls Control.Element.
If Control.Element is None, uiautomation searches the control in the control tree by the properties you supply.
uiautomation will raise a LookupError exception if it can't find the control in uiautomation.TIME_OUT_SECOND(default 10 seconds).
You can use Control.Exists(maxSearchSeconds, searchIntervalSeconds) to check whether a control Exists, this function doesn't raise any exception.
Control.Element will has a valid value if the control exists.
Call Control.Refind or Control.Exists to make Control.Element invalid again and uiautomation will starts a new search in the control tree.  

For example:  
...

**Comment by koroner1** [comment]
ok, thanks for answer and example
