### ISSUE TITLE
uiautomation 获取控件handle为0

### ISSUE THREAD

**Issue by qdwangjianjun** [yinkaisheng/Python-UIAutomation-for-Windows#83]
使用NativeWindowHandle 属性获取到的控件handle = 0，通过automation.py 查看控件，handle也是为0。 

![image](https://user-images.githubusercontent.com/40756962/60853734-fdfeaf00-a22f-11e9-9237-010702e62b9d.png)

**Comment by yinkaisheng** [comment]
不是问题，用微软Inspect看应该也是0。
