### ISSUE TITLE
Control.GetPattern(self, patternId: int)没有返回值，GetPattern(10002)经常取不到ValuePattern

### ISSUE THREAD

**Issue by wanglinwu2019** [yinkaisheng/Python-UIAutomation-for-Windows#85]
你好，我这有个界面里，里面有几个控件其它属性都是空，只有ValuePattern能区分，想用Compare=lambda control, depth: 'button_s.png' in control.GetPattern(10002).Value来获取控件，偶尔能获取到，大部分时间都报'NoneType' object has no attribute 'Value。查看documents，发现Control.GetPattern(self, patternId: int)没有返回值

**Comment by yinkaisheng** [comment]
如果不支持某个Pattern, GetPattern返回值就是None。你要自己判断啊：

Compare=lambda control, depth: control.GetPattern(10002) and 'button_s.png' in control.GetPattern(10002).Value
或者单独写个函数，不用lambda，减少一次调用control.GetPattern(10002)

**Comment by wanglinwu2019** [comment]
按这样操作解决了，非常感谢
