### ISSUE TITLE
Exists()函数判断控件花费的时间与参数时间不一致

### ISSUE THREAD

**Issue by Wang-zhipeng** [yinkaisheng/Python-UIAutomation-for-Windows#88]
1.  print(uiautomation.WindowControl(Name='qwe', searchDepth=1).Exists(1))
2.  print(uiautomation.WindowControl(Name='qwe').Exists(1))
当Window控件不存在时，第一行代码时间为1s左右， 但第二行时间每次都在6.8s左右。
请问Exist()函数依赖searchDepth参数吗？ 假如我想在1s内判断控件是否存在， 那么在定义控件时是不是都需要像WindowControl(Name='qwe', searchDepth=1)这样传入searchDepth参数而不是直接使用searchDepth的默认值呢？

**Comment by yinkaisheng** [comment]
这是正常的，最好都传入searchDepth参数，指定搜索深度。否则会搜索整个控件树，没找到才判断是否超时。如果整个控件树有成千上万个控件的话就会导致，实际时间就会大于所设定的时间。

**Comment by Wang-zhipeng** [comment]
感谢回复。您的项目给了我很大帮助，对您再次表示由衷的感谢！
