### ISSUE TITLE
不写日志可以不可以？

### ISSUE THREAD

**Issue by chenhan0055** [yinkaisheng/Python-UIAutomation-for-Windows#89]
您好  老师
我们用您的api在 windows上实现了一个自动化 （RPA）自动导出文件的动作
因为空间有点不够，老师您能教一个简便方法  不生成@automation.Log文件么？

非常感谢！

**Comment by yinkaisheng** [comment]
现在还不可以，我要修改一下才可以。但会导致之前代码不能用，api要改变。

**Comment by yinkaisheng** [comment]
auto.Logger.SetLogFile('') 不写log
