### ISSUE TITLE
uiautomation.py获取的控件树，有的控件ID识别不到

### ISSUE THREAD

**Issue by wanglinwu2019** [yinkaisheng/Python-UIAutomation-for-Windows#99]
app的页面定义文件，有一部分是这样的：

                    <tr> 
						<td></td>
                      	<td height="50"> 
                        	<div align="center" class="prompt_11" id="prompt">请输入身份证号</div>
                       </td>
                    </tr>
                    <tr> 
						<td name="handTd" id="iDCard_handTd"></td>
                      	<td background="../images/sub/keyboard_input2.gif" width="344" align="center">
                        	<input type="text" id="iDCard" name="iDCard" class="input_2" maxlength="18" size="25" value="" onclick="initKey(this, 18);" >
						</td>
                    </tr>

这部分定义的界面，在@AutomationLog.txt里，只有id="iDCard_handTd"和id="iDCard"这两个控件的id能识别出来，id="prompt"控件的id就识别不到。
       使用中发现，大部分的id都识别不到。
       操作系统是windows xp，打了补丁。
这是@AutomationLog.txt对应的部分：

 ControlType: DataItemControl    ClassName:     AutomationId:     Rect: (647,172,1003,222)[356x50]    Name: 请输入身份证号    Handle: 0x0(0)    Depth: 16    GridItemPattern.Row: 1    GridItemPattern.Column: 1    SupportedPattern: GridItemPattern LegacyIAccessiblePattern ScrollItemPattern
                                                                    ControlType: TextControl    ClassName:     AutomationId:     Rect: (741,180,916,214)[175x34]    Name: 请输入身份证号    Handle: 0x0(0)    Depth: 17    ValuePattern.Value:     SupportedPattern: LegacyIAccessiblePattern ValuePattern
                                                                ControlType: DataItemControl    ClassName:     AutomationId: iDCard_handTd    Rect: (569,222,647,306)[78x84]    Name:     Handle: 0x0(0)    Depth: 16    GridItemPattern.Row: 0    GridItemPattern.Column: 0    SupportedPattern: GridItemPattern LegacyIAccessiblePattern ScrollItemPattern
                                                                    ControlType: ImageControl    ClassName:     AutomationId:     Rect: (569,256,632,272)[63x16]    Name:     Handle: 0x0(0)    Depth: 17    SupportedPattern: LegacyIAccessiblePattern ScrollItemPattern
                                                                ControlType: DataItemControl    ClassName:     AutomationId:     Rect: (647,222,1003,306)[356x84]    Name:     Handle: 0x0(0)    Depth: 16    GridItemPattern.Row: 1    GridItemPattern.Column: 1    SupportedPattern: GridItemPattern LegacyIAccessiblePattern ScrollItemPattern
                                                                    ControlType: EditControl    ClassName:     AutomationId: iDCard    Rect: (671,250,966,276)[295x26]    Name:     Handle: 0x0(0)    Depth: 17    TextPattern.Text:     ValuePattern.Value:     SupportedPattern: LegacyIAccessiblePattern ScrollItemPattern TextPattern ValuePattern

**Comment by yinkaisheng** [comment]
不是问题，网页里的id和AutomationId没有对应关系。获取的控件树是由浏览器控制的，和浏览器实现有关。
